package com.strangeparticle.springboard.app.luther.toolcall

import com.strangeparticle.luther.toolcall.ToolCallRegistry

internal fun createSpringboardToolCallRegistry(): ToolCallRegistry = ToolCallRegistry().apply {
    register(ActivateColumnToolCallHandler())
    register(ActivateCoordinateToolCallHandler())
    register(ActivateCoordinatesToolCallHandler())
    register(ActivateRowToolCallHandler())
    register(AddAppGroupToolCallHandler())
    register(AddAppToolCallHandler())
    register(AddCommandActivatorToolCallHandler())
    register(AddEnvironmentToolCallHandler())
    register(AddGuidanceToolCallHandler())
    register(AddResourceToolCallHandler())
    register(AddUrlActivatorToolCallHandler())
    register(AddUrlTemplateActivatorToolCallHandler())
    register(ChangeAppGroupIdToolCallHandler())
    register(ChangeAppIdToolCallHandler())
    register(ChangeEnvironmentIdToolCallHandler())
    register(ChangeResourceIdToolCallHandler())
    register(ChangeResourceNameToolCallHandler())
    register(CloseTabToolCallHandler())
    register(CreateSpringboardToolCallHandler())
    register(CreateTabToolCallHandler())
    register(MoveActivatorToolCallHandler())
    register(OpenFromUrlToolCallHandler())
    register(OpenLocalFileToolCallHandler())
    register(RemoveActivatorToolCallHandler())
    register(RemoveAppGroupToolCallHandler())
    register(RemoveAppToolCallHandler())
    register(RemoveEnvironmentToolCallHandler())
    register(RemoveGuidanceToolCallHandler())
    register(RemoveResourceToolCallHandler())
    register(ReorderActivatorsToolCallHandler())
    register(ReorderAppGroupsToolCallHandler())
    register(ReorderAppsToolCallHandler())
    register(ReorderEnvironmentsToolCallHandler())
    register(ReorderResourcesToolCallHandler())
    register(RespondWithMessageToolCallHandler())
    register(SaveSpringboardToolCallHandler())
    register(UpdateActivatorToolCallHandler())
    register(UpdateAppGroupToolCallHandler())
    register(UpdateAppToolCallHandler())
    register(UpdateEnvironmentToolCallHandler())
    register(UpdateGuidanceToolCallHandler())
}
