package com.strangeparticle.springboard.app.ui

object TestTags {
    const val SPRINGBOARD_ICON = "springboardIcon"
    const val VERSION_DESIGNATOR = "versionDesignator"
    const val STATUS_BAR_SOURCE = "statusBarSource"
    const val RELOAD_BUTTON = "reloadButton"
    const val APP_DROPDOWN = "appDropdown"
    const val RESOURCE_DROPDOWN = "resourceDropdown"
    const val ENVIRONMENT_DROPDOWN = "environmentDropdown"
    const val TOAST_MESSAGE = "toastMessage"
    const val TOAST_SEVERITY_LABEL = "toastSeverityLabel"
    const val TOAST_DISMISS_BUTTON = "toastDismissButton"
    const val GRID_ENVIRONMENT_TITLE = "gridEnvironmentTitle"
    const val GRID_HEADER_RESIZE_THUMB = "gridHeaderResizeThumb"
    const val GRID_HEADER_RESIZE_GRIP_GLYPH = "gridHeaderResizeGripGlyph"
    const val SETTINGS_GEAR_ICON = "settingsGearIcon"
    const val SETTINGS_SCREEN = "settingsScreen"
    const val SETTINGS_BACK_BUTTON = "settingsBackButton"
    const val ACTIVE_SETTINGS_SCREEN = "activeSettingsScreen"
    const val ACTIVE_SETTINGS_BACK_BUTTON = "activeSettingsBackButton"
    const val SETTINGS_USE_CURRENT_FILE_BUTTON = "settingsUseCurrentFileButton"
    const val SETTINGS_CLEAR_BUTTON = "settingsClearButton"
    const val SETTINGS_OVERRIDE_WARNING = "settingsOverrideWarning"
    const val ZOOM_DROPDOWN = "zoomDropdown"

    fun settingsDropdown(settingKey: String) = "settingsDropdown_$settingKey"
    fun settingsDropdownOption(settingKey: String, optionId: String) = "settingsDropdownOption_${settingKey}_${optionId}"

    fun gridCell(appId: String, resourceId: String) = "gridCell_${appId}_${resourceId}"
    fun gridCellActivatorIndicator(appId: String, resourceId: String) = "gridCellActivator_${appId}_${resourceId}"
    fun gridCellGuidanceIndicator(appId: String, resourceId: String) = "gridCellGuidance_${appId}_${resourceId}"
    fun gridRowLabel(resourceId: String) = "gridRowLabel_${resourceId}"
    fun activeSettingsSourceLabel(displayName: String) = "activeSettingsSource_${displayName}"
    fun activeSettingsValue(displayName: String) = "activeSettingsValue_${displayName}"
}
